---
- name: Manage SFDC opportunities as Asana tasks
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/all

  # Run these pre_tasks to reduce the amount of api calls
  pre_tasks:
    - name: Read csv file and return a dict
      community.general.read_csv:
        path: "{{csv_file}}"
        skipinitialspace: true
        strict: false
      register: csvopps
      delegate_to: localhost

    - name: Get a list of all tasks in a project
      uri:
        url: "{{ asana_api }}/projects/{{asana_project_id}}/tasks"
        headers:
          Content-Type: application/json
          Authorization: "{{asana_token}}"
        method: GET
        validate_certs: "{{ validate_certs }}"
        status_code: 200
      register: project_tasks

  tasks:
    - name: Convert dict to list and Loop through each item
      include_tasks: manage-tasks.yml
      vars:
        close_date: "{{ csv_item['Close Date'] }}"
        created_date: "{{ csv_item['Created Date'] }}"
        customer_name: "{{ csv_item['Global Customer Name'] }}"
        description: "{{ csv_item['Description'] | default('') }}"
        fiscal_quarter: "{{ csv_item['Fiscal Quarter'] }}"
        forecast_category: "{{ csv_item['Forecast Category'] }}"
        next_step: "{{ csv_item['Next Step'] | default('') }}"
        opp_id: "{{ csv_item['Opportunity ID'] }}"
        opp_number: "{{ csv_item['Opportunity Number'] }}"
        opp_name: "{{ csv_item['Opportunity Name'] }}"
        opp_owner: "{{ csv_item['Opportunity Owner'] }}"
        opp_record_type: "{{ csv_item['Opportunity Record Type'] }}"
        products: "{{ csv_item['Products'] }}"
        reason: "{{ csv_item['Reason Closed/Lost'] | default('') }} - {{ csv_item['Reason Won/Lost (Sales Process)'] | default('') }} "
        syb: "{{ csv_item['1st Year Booking'] }}"
        tb: "{{ csv_item['Total Amount'] }}"
        tech_win_date: "{{ csv_item['Technical Win Date'] | default('') }}"
        # reset variables
        dict_var: {}
        techwon: false
      loop: "{{ csvopps.list }}"
      loop_control:
        loop_var: csv_item

      # count number of opportunities processed
    - name: Play Summary
      debug:
        msg: "Processed {{csvopps.list|count}} opps from ({{csv_file}})"
