---
- name: Manage SFDC opportunities as Asana tasks
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/all.yml
    # - "group_vars/{{region}}.yml"

  pre_tasks:
    - set_fact:
        num_ops: "{{ csvopps.list|count }}"

  tasks:
    - name: Log project_gid
      debug:
        var: project_gid
      failed_when: project_gid is not defined

    - name: Get a list of tasks in a project ({{ project_gid }})
      uri:
        url: "{{ asana_api }}/projects/{{ project_gid }}/tasks"
        headers:
          Content-Type: application/json
          Authorization: "{{ asana_token }}"
        method: GET
        validate_certs: "{{ validate_certs }}"
        status_code: 200
      register: project_tasks

    - name: Log project_tasks
      debug:
        var: project_tasks
        verbosity: 2
      failed_when: project_tasks is not defined

    - name: Count number of tasks found
      debug:
        var: project_tasks.json.data | count
      failed_when: project_tasks is not defined

    - name: Convert dict to list and Loop through each item to manage tasks
      include_tasks: manage-tasks.yml
      vars:
        opp_number: "{{ csv_item['Opportunity Number'] }}"
        syb: "{{ csv_item['SYB'] }}"
        tb: "{{ csv_item['TB'] }}"
        products: "{{ csv_item['Products'] }}"
        start_date: "{{ csv_item['Start Date'] }}"
        customer_name: "{{ csv_item['Global Customer Name'] }}"
        account_name: "{{ csv_item['Account Name'] }}"
        stage: "{{ csv_item['Stage'] }}"
        forecast_category: "{{ csv_item['Forecast Category'] }}"
        created_date: "{{ csv_item['Created Date'] }}"
        close_date: "{{ csv_item['Close Date'] }}"
        channel: "{{ csv_item['Channel'] }}"
        opp_name: "{{ csv_item['Opportunity Name'] }}"
        opp_id: "{{ csv_item['Opportunity ID'] }}"
        opp_record_type: "{{ csv_item['Opportunity Record Type'] | default('') }}"
        fiscal_quarter: "{{ csv_item['Fiscal Quarter'] | default('') }}"

        # description: "{{ csv_item['Description'] | default('') }}"
        # next_step: "{{ csv_item['Next Step'] | default('') }}"
        #opp_owner: "{{ csv_item['Opportunity Owner'] }}"
        #tech_win_date: "{{ csv_item['Technical Win Date'] }}"
        # reason1: "{{ csv_item['Reason Closed/Lost'] }}"
        # reason2: "{{ csv_item['Reason Won/Lost (Sales Process)'] }}"
        # reseller: "{{ csv_item['Reseller'] }}"
        # leadsource: "{{ csv_item['Lead Source'] }}"
        #distributor: "{{ csv_item['Financial Partner'] }}"
      loop: "{{ csvopps.list }}"
      loop_control:
        loop_var: csv_item
        index_var: csv_index

      # count number of opportunities processed
    - name: Play Summary
      debug:
        msg: "Processed {{ csvopps.list|count }} opps"
