---
- name: Manage SFDC opportunities as Asana tasks
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/all.yml
    - "group_vars/{{region}}.yml"

  pre_tasks:
    - set_fact:
        num_ops: "{{ csvopps.list|count }}"

  tasks:
    - name: Log project_gid
      debug:
        var: project_gid
      failed_when: project_gid is not defined

    - name: Get a list of tasks in a project ({{asana_project_name}})
      uri:
        url: "{{ asana_api }}/projects/{{project_gid}}/tasks"
        headers:
          Content-Type: application/json
          Authorization: "{{asana_token}}"
        method: GET
        validate_certs: "{{ validate_certs }}"
        status_code: 200
      register: project_tasks

    - name: Count number of tasks found
      debug:
        var: project_tasks.json.data | count
      failed_when: project_tasks is not defined

    - name: Convert dict to list and Loop through each item
      include_tasks: manage-tasks.yml
      vars:
        products: "{{ csv_item['Products'] }}"
        product_detail: "{{ csv_item['Product Detail'] }}"
        syb: "{{ csv_item['1st Year Booking'] }}"
        tb: "{{ csv_item['Total Amount'] }}"
        start_date: "{{ csv_item['Start Date'] }}"
        programs: "{{ csv_item['Programs'] }}"
        na_region: "{{ csv_item['Region'] }}"
        subregion: "{{ csv_item['Subregion'] }}"
        opp_number: "{{ csv_item['Opportunity Number'] }}"
        customer_name: "{{ csv_item['Global Customer Name'] }}"
        opp_name: "{{ csv_item['Opportunity Name'] }}"
        opp_owner: "{{ csv_item['Opportunity Owner'] }}"
        fiscal_period: "{{ csv_item['Fiscal Period'] }}"
        close_date: "{{ csv_item['Close Date'] }}"
        forecast_category: "{{ csv_item['Forecast Category'] }}"
        stage: "{{ csv_item['Stage'] }}"
        probability: "{{ csv_item['Probability'] }}"
        reseller: "{{ csv_item['Reseller'] }}"
        next_step: "{{ csv_item['Next Step'] }}"
        opp_id: "{{ csv_item['Opportunity ID'] }}"
      loop: "{{ csvopps.list }}"
      loop_control:
        loop_var: csv_item
        index_var: csv_index

      # count number of opportunities processed
    - name: Play Summary
      debug:
        msg: "Processed {{csvopps.list|count}} opps"
